### ISSUE TITLE
Remove and update default seed nodes

### ISSUE THREAD

**Issue by heyrhett** [WhaleCoinOrg/WhaleCoin#4]

**Comment by hTrap** [comment]
https://github.com/WhaleCoinOrg/WhaleCoin/blob/64eb4d30600366ddc34314c10e949faf0b908ca7/mobile/geth.go#L79-L86

@heyrhett you meant this, right?

**Comment by heyrhett** [comment]
here:
https://github.com/WhaleCoinOrg/WhaleCoin/blob/64eb4d30600366ddc34314c10e949faf0b908ca7/params/bootnodes.go

Probably other places also?
