### ISSUE TITLE
Slow Start

### ISSUE THREAD

**Issue by heyrhett** [WhaleCoinOrg/WhaleCoin#7]
The difficulty of WhaleCoin is self-adjusting.

However, we don't know the initial hashrate that will come online in the first few minutes, and it is hard to guess what it will be.

Without a slow start, it is possible that one miner could come online and take all of the first 1000 blocks.  Therefore, we should limit the reward for the first 1000 blocks to give all the initial miners time to come online and start mining fairly.

**Comment by hTrap** [comment]
What reward do you think is fair in this scenario? Also Why don't we limit it in 5k-10k blocks range?

**Comment by heyrhett** [comment]
How fast does the difficulty adjust?  What happens if someone tries to mine the initial chain with 2000 GPUs? How many blocks can they mine in 5 minutes?

**Comment by hTrap** [comment]
We can increase the time required to mine a block for initial 1000 blocks as 60seconds
